### ISSUE TITLE
undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by bechtoldt** [theforeman/foreman-one#4]
Creating a new VM with Foreman doesn't work. After submitting the data, Foreman fails with the message: 

undefined method `id' for nil:NilClass

Foreman: 1.6.0-RC1 
OS: Debian Wheezy
Plugin version: latest
ONE version: 4.8.0
Foreman production log: https://np.adm.sx/view/917177be

Could you check this please? Also I'm asking myself what the parameters b0e and foob0e in line 6 are for. :)

**Comment by b0e** [comment]
Yes i'm still working on this project. I tested this with foreman-1.6.1 and OpenNebula 4.10.1 and i'm using this with https://github.com/netways/fog.git on branch feature/improved_network_flavor_models.

Sometimes it is hard to get changes into the fog master, even if only change the opennebula part. It would be nice if someone else would join this project (or [netways/fog](https://github.com/NETWAYS/fog))

**Comment by domcleal** [comment]
There's a trend to splitting fog providers out into their own gems... while it means somebody has to maintain it, it might be worth trying to find a few people to head it up, as then you can develop more quickly away from fog core.

**Comment by pmartins21** [comment]
That sounds great. I'm not familiar with maintaining, but maybe someone of the OpenNebula Team could do this job?

**Comment by mmoll** [comment]
@b0e could you (or NETWAYS) kick that off over at fog?

**Comment by stevie-** [comment]
Hello, I'm testing foreman 1.7.2 with opennebula 4.6.2 

I fixed several code issues and now I ran into the postgresql integer uuid issue. 
To fix this "operator does not exist: character varying = integer " we just need to quote the id we get from opennebula to write it into the uuid db of foreman. 
the Foreman_one plugin should take care of this or?

my changes:
Fix template creation:
  You can add your \" escapes gsub here, if you need it
lib/fog/opennebula/models/compute/flavor.rb
```
        def get_raw
          return "" unless raw
          ret = "RAW=#{raw}\n"
          ret.gsub!(/\{/, '[')
          ret.gsub!(/\}/, ']')
          ret.gsub!(/>/,'')
          ret
        end
```

**Comment by mmoll** [comment]
@stevie- please open pull requests for your fixes. Sadly personally, I can't say anything to it, as I'm not using OpenNebula, we nned to rely on ONE users here.

**Comment by mmoll** [comment]
what's the status here?

**Comment by mmoll** [comment]
no reactions, closing.
