### ISSUE TITLE
Clicking "Associate" on a ONE VM gives DB error

### ISSUE THREAD

**Issue by tverhoeven** [theforeman/foreman-one#8]
I'm getting this error with the current git head when trying to associating a ONE VM in Foreman:

Warning!
PGError: ERROR: operator does not exist: character varying = integer LINE 1: ..."hosts"."compute_resource_id" = 1 AND "hosts"."uuid" IN (21) ^ HINT: No operator matches the given name and argument type(s). You might need to add explicit type casts. : SELECT COUNT(*) FROM "hosts" WHERE "hosts"."organization_id" IN (1) AND "hosts"."location_id" IN (2) AND "hosts"."type" IN ('Host::Managed') AND "hosts"."compute_resource_id" = 1 AND "hosts"."uuid" IN (21)

This is on Foreman 1.9.3, Foreman-one from git head of 26/11 and ONE 4.14.2

**Comment by domcleal** [comment]
I opened a PR at #10 with a fix we've used elsewhere, would you be able to test it and report back please?

**Comment by tverhoeven** [comment]
This PR does not seem to help. I'm still getting exactly the same error. I've verified that the changes are on the system.

Other suggestions?

**Comment by domcleal** [comment]
Hm yes, now I look closer I think that would only fix errors on creation (as it did for DO), but we don't seem to have such problems in this plugin.  Fixing association is going to require a change in Foreman core, as I don't think it's safe to override the code from the plugin (it broke things in DO when we tried).

Could you try changing the `scope :for_vm` line in /usr/share/foreman/app/models/host/managed.rb to:

    scope :for_vm, ->(cr,vm) { where(:compute_resource_id => cr.id, :uuid => Array.wrap(vm).compact.map(&:identity).map(&:to_s)) }

**Comment by tverhoeven** [comment]
That does seem to make a difference. Now I'm getting this error:

Warning!
PGError: ERROR: column hosts.mac does not exist LINE 1: ...n_id" IN (1) AND "hosts"."location_id" IN (2) AND "hosts"."m... ^ : SELECT "hosts".* FROM "hosts" WHERE "hosts"."type" IN ('Host::Managed') AND "hosts"."organization_id" IN (1) AND "hosts"."location_id" IN (2) AND "hosts"."mac" = '02:00:0a:43:4b:0a' LIMIT 1

But if this is stuff that needs to be fixed in core then I guess we need to involve some other people.

**Comment by domcleal** [comment]
> That does seem to make a difference. Now I'm getting this error:
> 
> Warning!
> PGError: ERROR: column hosts.mac does not exist

This is some out of date code.  Change the `associated_host` as per #12.

> But if this is stuff that needs to be fixed in core then I guess we need to involve some other people.

That's OK, I'll send a patch over there, that's my area of expertise!

**Comment by domcleal** [comment]
> But if this is stuff that needs to be fixed in core then I guess we need to involve some other people.
> 
> That's OK, I'll send a patch over there, that's my area of expertise!

Submitted https://github.com/theforeman/foreman/pull/2940 to fix this.

**Comment by tverhoeven** [comment]
Yes, now the association works. Thank for the help!

**Comment by mmoll** [comment]
All the needed patches were merged, http://theforeman.org/issues/12623 is scheduled for Foreman core 1.10.1 to fully resolve this problem.
