### ISSUE TITLE
NoMethodError on linking compute profile to a ONE template

### ISSUE THREAD

**Issue by tverhoeven** [theforeman/foreman-one#9]
I'm getting this error when linking a Foreman compute profile to a ONE template:

NoMethodError
undefined method `vm_description' for #<Fog::Compute::OpenNebula::Server:0x007fb5ed958a80>
/opt/rh/ruby193/root/usr/share/gems/gems/activesupport-3.2.8/lib/active_support/core_ext/object/try.rb:36:in `try'
/usr/share/foreman/app/models/compute_attribute.rb:29:in `pretty_vm_attrs'
/usr/share/foreman/app/models/compute_attribute.rb:35:in `update_name'
/opt/rh/ruby193/root/usr/share/gems/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:440:in `_run__2065276289675235259__save__3091578048556141734__callbacks'

This is with Foreman 1.9.3, foreman-one from git master of 26/11 and ONE 4.14.2 on CentOS 7.

I'm willing to test everything you trow at me ;)

**Comment by domcleal** [comment]
Please give #10 a try.

**Comment by tverhoeven** [comment]
That seems to help, but now I'm getting another error:

NameError
undefined local variable or method `cpus' for #<Fog::Compute::OpenNebula::Server:0x007fb671777d68>
/opt/rh/ruby193/root/usr/share/gems/gems/foreman_one-0.3/app/models/concerns/fog_extensions/opennebula/server.rb:27:in `vm_description'
/opt/rh/ruby193/root/usr/share/gems/gems/activesupport-3.2.8/lib/active_support/core_ext/object/try.rb:36:in `try'
/usr/share/foreman/app/models/compute_attribute.rb:29:in `pretty_vm_attrs'
/usr/share/foreman/app/models/compute_attribute.rb:35:in `update_name'
/opt/rh/ruby193/root/usr/share/gems/gems/activesupport-3.2.8/lib/active_support/callbacks.rb:440:in `_run__1108326430850112639__save__1943021450898574728__callbacks'

But were are making progress, tx!

**Comment by domcleal** [comment]
Ah, I think I should have written `cpu` instead of `cpus`.  Can you try:

    _("%{cpus} CPUs and %{memory} memory") % {:cpus => cpu, :memory => number_to_human_size(memory.to_i)}

**Comment by tverhoeven** [comment]
That also seemed to work, on to the next step:

Warning!
undefined method `number_to_human_size' for #<Fog::Compute::OpenNebula::Server:0x0000000e7cdf90>

**Comment by domcleal** [comment]
Oops, add a `include ActionView::Helpers::NumberHelper` under the `extend` line.  Updated the PR too.

**Comment by tverhoeven** [comment]
Yes, now I'm no longer getting an error and it seems the link is made. I'll test a bit more to see if this actually works now.
Thanks!
